### ISSUE TITLE
Can you explain the structure of the tree?

### ISSUE THREAD

**Issue by LikeMJ** [andylamp/BPlusTree#11]
I don't understand several page types，for example，"overflow page" and  "lookup page overflow page"?  Also, I don't quite understand the parameters of class BPlusConfiguration.

**Comment by andylamp** [comment]
Hi there - thanks for the comment. Unfortunately, at this time I do not have time to provide detailed explanation of this structure, it is provided AS-IS without any warranty. However, it is based on the version of B+ Tree described in [CLRS](https://mitpress.mit.edu/books/introduction-algorithms-fourth-edition), perhaps you can read the respective chapter in that book to get a better understanding.

I am closing this as off-topic, but if you feel otherwise you can re-open the issue.

Thanks!
