### ISSUE TITLE
Why only positive keys are allowed?

### ISSUE THREAD

**Issue by youkaichao** [andylamp/BPlusTree#3]
In your project, it says:
`@throws NumberFormatException is thrown when we have an invalid key value (we only allow >= 0 as keys`

Why?

**Comment by andylamp** [comment]
Hi, thanks for asking - limiting the keys to only values >= 0 was due to the fact that this particular project - along with two others - was developed as a part of a file system and the keys were the `inode`s tracked and the payload was the `inode`s contents; hence, this "limitation" was a design requirement rather than a quirk of the data-structure itself. As it is said in the `README`, this is a trimmed down version of a component of the aforementioned file-system project,

hope this helps...

edit: am closing the issue since this is not technically a bug or something.
