### ISSUE TITLE
potential performance gain

### ISSUE THREAD

**Issue by youkaichao** [andylamp/BPlusTree#6]
Hey, maybe you can try out some techniques like **writing int / double etc into a byte array and then write it into the file** rather than invoking **treeFile.writeInt/writeDouble etc** for several times. For my project, such an optimization saves 90% time.

**Comment by andylamp** [comment]
hi - thanks; it was done this way in order to ensure at each write the tree was in a consistent state and to keep things simple. Should you want to implement buffered bulk writes along with corruption protection against crashes while writing the buffer you are more than welcome to do so :)

btw: closing the issue, but willing to reopen it if you have a pull request to do.
